### ISSUE TITLE
Array index out of bounds when opening GUI's

### ISSUE THREAD

**Issue by rheimus** [simeonradivoev/MatterOverdrive#350] opened 2015-12-07 03:12 UTC
Getting out of bounds when opening GUI's on a server with a bunch of mods possibly due to matteroverdrive/gui/MOGuiBase.java defining a size of 3 when the pages arrays are created. Appears that the client is trying to access index 34 which would be well out of bounds of 3.

Mods are essentially Agrarian Skies 2 + Ender IO.

*Only occurs when connected to a server, singleplayer has no issue

**Comment by simeonradivoev** [comment] 2015-12-07 06:57
Could you possibly link the log file? Also what specific GUI is this happening to and what version of the mod are you using? This may be to another bug connected to player inventory size.

**Comment by rheimus** [comment] 2015-12-08 03:13
http://filebin.ca/2PCFz8aUSeZ0/fml-client-2.log

Specifically occurs when accessing the handheld items, MatterScanner and DataPad.
May also have something to do with the pack having both COFHlib and COFHcore installed at the same time... currently testing that.

**Comment by simeonradivoev** [comment] 2015-12-08 12:07
The out of bound error is quite the silly and strange bug. I was caused by MC trying to put items in the fake containers made by handheld items. I don't know why but it was fixed in 97028befa4fe6ae37b0f6747bc2a5048583a8634.

As for the null pointer exception is just a debug message that I forgot to disable it by disabling the debug message config option. It an indication that some itemstacks return a null exception when getting their unlocalized names. That was fixed as well by making the matter registry use not unlocalized names but game registry names in 949399b7e42df50d346fc94a710560b72f2a119b.

You can try the dev builds or you can wait for me to release a new beta version.

**Closed by simeonradivoev** 2015-12-08 12:07 UTC
