### ISSUE TITLE
Compatability with NotEnoughIDs

### ISSUE THREAD

**Issue by YukiRainee** [simeonradivoev/MatterOverdrive#655] opened 2017-03-19 08:52 UTC
Forgive me if this has been addressed already but it seems your mod dosen't like notenoughids as it keeps throwing this crash report at me when using it along with the modpack http://pastebin.com/T8DvVxLx

**Comment by shadowfacts** [comment] 2017-03-19 12:42
Duplicate of #628.

**Closed as completed by shadowfacts** 2017-03-19 12:42 UTC
Labels: duplicate
