### ISSUE TITLE
Full on Client Crash to desk top

### ISSUE THREAD

**Issue by Tyrantin** [simeonradivoev/MatterOverdrive#674] opened 2017-03-31 22:32 UTC
[crash-2017-03-29_11.00.44-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/887079/crash-2017-03-29_11.00.44-client.txt)

**Comment by Muirrum** [comment] 2017-03-31 22:45
Can you give us some form of information as to what you were doing at the time?

**Comment by shadowfacts** [comment] 2017-03-31 23:04
Duplicate of #636. This is an issue that you yourself reported, don't report stuff multiple times.

**Closed as completed by shadowfacts** 2017-03-31 23:04 UTC
Labels: duplicate
