### ISSUE TITLE
Bug with Android Compass

### ISSUE THREAD

**Issue by Epicossetty** [simeonradivoev/MatterOverdrive#448] opened 2016-02-19 02:27 UTC
I've been having this problem several times this past month. If I unlock the android upgrade that requires a compass, my game whitescreens and crashes. I play on a server, so the server was able to reset my player data. However, I have earned several of your awesome custom legendary armors, as well as a plethora of other modded items, so I really don't want that server data deleted again. Is there any way to have this feature rectified? Thanks.

**Comment by simeonradivoev** [comment] 2016-02-19 11:56
You are referring to the minimap ability. Can you post a client crash log?
Also there is a way to change the player data to remove learned abilities. You can also use a command to do that but I suppose that's not possible if you crash on login.

**Comment by Epicossetty** [comment] 2016-02-19 13:24
Indeed. If I may ask, what is this way to change the player data? 
Also, it seems as though the crash is a result of a null pointer exception.

[crash-2016-02-18_20.04.50-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/138005/crash-2016-02-18_20.04.50-client.txt)

**Comment by simeonradivoev** [comment] 2016-02-19 13:25
This is caused by Custom NPCs. I think they fixed it, but I'm not quite sure. As for the player data it is stored in a file that can be edited with a NBT editor. It should be in the playerdata.dat or something.

**Comment by Epicossetty** [comment] 2016-02-19 13:32
Ok. I'll talk to my friend, the server owner, and let you know if it gets fixed. Thanks a bunch! Love the mod, and also: are you going to do anything about those structures listed in NEI? Cause I'd LOVE to see them, as our server is pretty story-driven and a bit RP-ish, with CustomNPCs and all.

**Comment by ajthemacboy** [comment] 2016-02-19 22:31
Offtopic: What exactly are ships for? What and how do you use the Starmap? Can you add documentation for them?

**Comment by simeonradivoev** [comment] 2016-02-19 22:31
The star map is not yet implemented

**Comment by ajthemacboy** [comment] 2016-02-19 22:32
I'm using the 1.7.10 0.4.1 version compiled from source and the graphics sure are epic, can't wait to use it!

**Comment by shadowfacts** [comment] 2016-02-19 22:36
@ajthemacboy please stop posting off topic in issues. If you want to talk about the mod, you can go to the #matteroverdrive IRC channel on esper.

**Comment by simeonradivoev** [comment] 2016-02-21 14:31
Closed in favor of #454

**Closed by simeonradivoev** 2016-02-21 14:31 UTC
Labels: fixed?, mod compatibility  bug
