### ISSUE TITLE
RenderWeaponsBeam

### ISSUE THREAD

**Issue by knoxhack** [simeonradivoev/MatterOverdrive#673] opened 2017-03-28 01:13 UTC
Client crash on server: 
Forge: 1.10.2 - 12.18.3.2254
Crash log:
https://gist.github.com/knoxhack/f76e221743e597a8e5210cf98fb5d1af

**Comment by shadowfacts** [comment] 2017-03-28 14:23
Duplicate of #657.

Please search the issue tracker before you submit something to see if you're submitting a duplicate.

**Closed as completed by shadowfacts** 2017-03-28 14:23 UTC
Labels: duplicate
