### ISSUE TITLE
A couple of bugs.

### ISSUE THREAD

**Issue by bird1000000** [simeonradivoev/MatterOverdrive#515] opened 2016-05-24 08:53 UTC
Brief explanation of problem:

1. Game crashes in creative menu
2. Game crashes when scrolling down to MO in JEI (Probably the same as 1)
3. Game crashes when loading super flat water world. 

Steps to reproduce:

1. Go in creative and click the right arrow and the game will crash.
2. Scroll downwards on JEI untill you reach matter overdrive, where it would crash.
3. Make a super flat world with the water world present and the game will crash.

Crash report paste (if any) on [gist](gist.github.com):

Pastebin:
1. http://pastebin.com/DH28YJQv
2. http://pastebin.com/529HWFXJ
3. http://pastebin.com/hMmqv6E0
Gist:
1. https://gist.github.com/bird1000000/cc53385f9dcf1de9e0b89eae5827505e
2. https://gist.github.com/bird1000000/43e4aded55537436524c7af602ab5fda
3. https://gist.github.com/bird1000000/4695565a88a171ece16f71738bc794fc 

MatterOverdrive version:
MatterOverdrive-1.9-0.4.3-build-50 (Latest)

Minecraft version:
1.9
1.9-forge12.16.1.1907 (Latest)

**Comment by shadowfacts** [comment] 2016-05-24 13:16
The third crash _could not_ happen unless there was a network switch in the world.

Also, goddamn the reobfuscator really needs a rewrite >.<

**Comment by shadowfacts** [comment] 2016-07-22 23:12
Duplicate of #563

**Closed by shadowfacts** 2016-07-22 23:12 UTC
Labels: bug, duplicate
