### ISSUE TITLE
Bucket fill crash

### ISSUE THREAD

**Issue by ryuknightofflame** [simeonradivoev/MatterOverdrive#662] opened 2017-03-21 22:25 UTC
When clicking with bucket on solid/non bucketable block the game crashes.

java.lang.NullPointerException: Unexpected error
	at matteroverdrive.handler.BucketHandler.onBucketFill(BucketHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_411_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:366)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at matteroverdrive.handler.BucketHandler.onBucketFill(BucketHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_411_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:366)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['<PROFILE NAME>'/396, l='MpServer', x=295.17, y=5.00, z=126.85]]
	Chunk stats: MultiplayerChunkCache: 438, 438
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (88,64,256), Chunk: (at 8,4,0 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 314683 game time, 532793 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 125 total; [EntityPig['Pig'/513, l='MpServer', x=329.50, y=72.00, z=183.05], EntityPig['Pig'/522, l='MpServer', x=341.24, y=66.00, z=62.68], EntityPig['Pig'/527, l='MpServer', x=325.46, y=75.00, z=202.21], EntityPig['Pig'/529, l='MpServer', x=350.20, y=74.00, z=184.21], EntityPig['Pig'/530, l='MpServer', x=345.47, y=73.00, z=178.30], EntitySkeleton['Skeleton'/1302, l='MpServer', x=323.50, y=22.00, z=190.50], EntityCreeper['Creeper'/1827, l='MpServer', x=360.50, y=38.00, z=158.50], EntitySkeleton['Skeleton'/1838, l='MpServer', x=356.50, y=26.00, z=116.50], EntityZombie['Zombie'/1335, l='MpServer', x=334.81, y=13.00, z=184.49], EntityZombie['Zombie'/1847, l='MpServer', x=294.50, y=22.00, z=74.50], EntityZombie['Zombie'/1592, l='MpServer', x=370.50, y=29.00, z=190.50], EntityCreeper['Creeper'/1848, l='MpServer', x=295.50, y=22.00, z=75.50], EntityZombie['Zombie'/1593, l='MpServer', x=370.50, y=29.00, z=190.50], EntityZombie['Zombie'/1338, l='MpServer', x=340.50, y=12.00, z=173.50], EntitySkeleton['Skeleton'/1597, l='MpServer', x=214.50, y=28.00, z=184.50], EntityZombie['Zombie'/1342, l='MpServer', x=343.50, y=12.00, z=175.50], EntitySkeleton['Skeleton'/1598, l='MpServer', x=214.50, y=28.00, z=184.50], EntityPig['Pig'/330, l='MpServer', x=223.25, y=74.00, z=63.48], EntityPig['Pig'/332, l='MpServer', x=222.68, y=68.00, z=111.57], EntityPig['Pig'/334, l='MpServer', x=218.55, y=58.00, z=157.45], EntityPig['Pig'/335, l='MpServer', x=216.55, y=66.00, z=152.50], EntityPig['Pig'/336, l='MpServer', x=221.22, y=65.00, z=160.49], EntityPig['Pig'/338, l='MpServer', x=216.47, y=61.00, z=161.25], EntityBat['Bat'/1877, l='MpServer', x=273.89, y=54.23, z=122.19], EntitySkeleton['Skeleton'/1623, l='MpServer', x=215.46, y=15.00, z=185.76], EntitySkeleton['Skeleton'/1882, l='MpServer', x=299.50, y=52.00, z=96.50], EntityPig['Pig'/353, l='MpServer', x=232.78, y=68.00, z=85.51], EntityPig['Pig'/354, l='MpServer', x=227.41, y=68.00, z=104.72], EntitySkeleton['Skeleton'/1634, l='MpServer', x=338.50, y=19.00, z=166.50], EntityPig['Pig'/355, l='MpServer', x=239.47, y=69.00, z=127.72], EntityPig['Pig'/356, l='MpServer', x=235.80, y=69.00, z=127.81], EntityPig['Pig'/357, l='MpServer', x=231.53, y=68.00, z=148.29], EntityPig['Pig'/358, l='MpServer', x=228.22, y=68.00, z=149.24], EntityPig['Pig'/359, l='MpServer', x=227.28, y=65.00, z=169.86], EntityPig['Pig'/360, l='MpServer', x=237.42, y=61.96, z=192.16], EntityPig['Pig'/362, l='MpServer', x=246.74, y=67.00, z=91.54], EntityPig['Pig'/363, l='MpServer', x=241.21, y=67.00, z=159.71], EntityCreeper['Creeper'/1899, l='MpServer', x=239.50, y=52.00, z=52.50], EntityPig['Pig'/364, l='MpServer', x=240.93, y=63.00, z=186.89], EntityCreeper['Creeper'/1900, l='MpServer', x=373.50, y=30.00, z=188.50], EntitySkeleton['Skeleton'/1902, l='MpServer', x=336.50, y=15.00, z=123.50], EntitySkeleton['Skeleton'/1903, l='MpServer', x=337.50, y=15.00, z=125.50], EntityPig['Pig'/625, l='MpServer', x=347.52, y=71.00, z=192.28], EntityPig['Pig'/373, l='MpServer', x=269.45, y=63.00, z=167.45], EntityPig['Pig'/374, l='MpServer', x=270.65, y=64.00, z=200.73], EntityPig['Pig'/379, l='MpServer', x=276.51, y=66.00, z=69.79], EntitySkeleton['Skeleton'/383, l='MpServer', x=280.77, y=52.00, z=104.52], EntitySkeleton['Skeleton'/1407, l='MpServer', x=324.50, y=23.00, z=119.50], EntityBat['Bat'/1666, l='MpServer', x=347.95, y=33.14, z=132.36], EntityPig['Pig'/387, l='MpServer', x=283.54, y=63.00, z=162.73], EntityPig['Pig'/388, l='MpServer', x=285.78, y=64.00, z=169.49], EntityPig['Pig'/389, l='MpServer', x=280.27, y=64.00, z=200.82], EntityCreeper['Creeper'/1925, l='MpServer', x=275.50, y=58.00, z=113.50], EntityCreeper['Creeper'/1926, l='MpServer', x=276.50, y=58.00, z=111.50], EntityCreeper['Creeper'/1927, l='MpServer', x=278.50, y=58.00, z=112.50], EntityCreeper['Creeper'/1928, l='MpServer', x=272.50, y=58.00, z=113.50], EntityCreeper['Creeper'/1673, l='MpServer', x=337.50, y=32.00, z=128.50], EntityZombie['Zombie'/1674, l='MpServer', x=336.79, y=32.00, z=130.56], EntityZombie['Zombie'/1675, l='MpServer', x=336.50, y=32.00, z=128.50], EntityZombie['Zombie'/1676, l='MpServer', x=341.50, y=32.00, z=129.50], EntityPig['Pig'/398, l='MpServer', x=264.79, y=65.00, z=62.52], EntityPig['Pig'/399, l='MpServer', x=283.71, y=66.00, z=51.76], EntityPig['Pig'/400, l='MpServer', x=284.53, y=67.00, z=55.25], EntityBat['Bat'/1172, l='MpServer', x=345.03, y=35.13, z=133.04], EntityPig['Pig'/406, l='MpServer', x=241.46, y=75.00, z=61.73], EntityCreeper['Creeper'/1942, l='MpServer', x=323.50, y=58.00, z=195.50], EntitySkeleton['Skeleton'/408, l='MpServer', x=294.32, y=52.00, z=63.62], EntityCreeper['Creeper'/410, l='MpServer', x=299.20, y=51.00, z=95.57], EntityPig['Pig'/413, l='MpServer', x=299.76, y=67.00, z=69.69], EntitySkeleton['Skeleton'/1951, l='MpServer', x=344.50, y=38.00, z=199.50], EntityPig['Pig'/416, l='MpServer', x=298.73, y=64.00, z=163.41], EntityBat['Bat'/1697, l='MpServer', x=215.06, y=16.11, z=159.76], EntityPlayerSP['<PROFILE NAME>'/396, l='MpServer', x=295.17, y=5.00, z=126.85], EntityCreeper['Creeper'/428, l='MpServer', x=294.78, y=20.00, z=151.53], EntityZombie['Zombie'/940, l='MpServer', x=325.35, y=12.00, z=150.35], EntityZombie['Zombie'/429, l='MpServer', x=294.35, y=31.00, z=153.35], EntityZombie['Zombie'/1966, l='MpServer', x=296.50, y=31.00, z=80.50], EntityZombie['Zombie'/1455, l='MpServer', x=304.19, y=30.00, z=137.63], EntityZombie['Zombie'/1456, l='MpServer', x=295.50, y=29.00, z=147.50], EntityBat['Bat'/1971, l='MpServer', x=225.01, y=49.08, z=73.76], EntityZombie['Zombie'/1718, l='MpServer', x=356.50, y=26.00, z=116.50], EntitySpider['Spider'/1468, l='MpServer', x=323.89, y=26.00, z=127.89], EntityCreeper['Creeper'/1725, l='MpServer', x=334.50, y=17.00, z=102.50], EntityZombie['Zombie'/1726, l='MpServer', x=318.50, y=52.00, z=125.50], EntitySpider['Spider'/1471, l='MpServer', x=320.70, y=27.00, z=124.70], EntityZombie['Zombie'/1727, l='MpServer', x=318.50, y=52.00, z=124.50], EntityPig['Pig'/459, l='MpServer', x=313.50, y=71.00, z=198.50], EntityPig['Pig'/460, l='MpServer', x=314.37, y=72.00, z=199.27], EntitySheep['Sheep'/461, l='MpServer', x=319.37, y=75.00, z=192.70], EntityCreeper['Creeper'/469, l='MpServer', x=298.70, y=51.00, z=96.55], EntitySkeleton['Skeleton'/472, l='MpServer', x=319.46, y=11.00, z=121.27], EntityCreeper['Creeper'/1756, l='MpServer', x=331.70, y=32.00, z=184.88], EntityCreeper['Creeper'/1757, l='MpServer', x=333.50, y=32.00, z=186.50], EntityCreeper['Creeper'/1246, l='MpServer', x=323.38, y=12.00, z=167.53], EntityCreeper['Creeper'/1758, l='MpServer', x=330.49, y=31.00, z=180.84], EntityZombie['Zombie'/1759, l='MpServer', x=359.51, y=39.00, z=156.30], EntityPig['Pig'/480, l='MpServer', x=312.26, y=67.00, z=59.30], EntityZombie['Zombie'/1760, l='MpServer', x=350.50, y=44.00, z=149.78], EntityPig['Pig'/481, l='MpServer', x=302.69, y=65.00, z=52.49], EntityZombie['Zombie'/1761, l='MpServer', x=362.70, y=39.00, z=156.41], EntityZombie['Zombie'/484, l='MpServer', x=311.27, y=20.00, z=151.44], EntitySkeleton['Skeleton'/486, l='MpServer', x=316.49, y=12.00, z=118.21], EntitySheep['Sheep'/487, l='MpServer', x=308.41, y=63.00, z=118.09], EntitySheep['Sheep'/488, l='MpServer', x=308.07, y=63.00, z=121.78], EntityCow['Cow'/489, l='MpServer', x=308.07, y=63.00, z=120.77], EntityCow['Cow'/490, l='MpServer', x=308.61, y=63.00, z=117.07], EntityCow['Cow'/491, l='MpServer', x=313.62, y=63.00, z=123.04], EntityCow['Cow'/492, l='MpServer', x=311.55, y=63.00, z=117.37], EntityCow['Cow'/493, l='MpServer', x=310.43, y=63.00, z=118.05], EntityCow['Cow'/494, l='MpServer', x=311.35, y=63.00, z=122.74], EntityCow['Cow'/495, l='MpServer', x=314.53, y=63.00, z=119.85], EntityPig['Pig'/496, l='MpServer', x=314.44, y=63.00, z=117.70], EntityPig['Pig'/497, l='MpServer', x=308.07, y=63.00, z=122.91], EntityPig['Pig'/498, l='MpServer', x=308.07, y=63.00, z=119.76], EntityPig['Pig'/499, l='MpServer', x=310.41, y=63.00, z=117.07], EntityPig['Pig'/500, l='MpServer', x=308.07, y=63.00, z=123.92], EntityPig['Pig'/501, l='MpServer', x=309.49, y=63.00, z=118.01], EntitySheep['Sheep'/505, l='MpServer', x=315.30, y=74.00, z=191.32], EntityZombie['Zombie'/1273, l='MpServer', x=337.50, y=51.00, z=143.50], EntitySheep['Sheep'/506, l='MpServer', x=318.46, y=75.00, z=197.24], EntityZombie['Zombie'/1274, l='MpServer', x=340.50, y=51.00, z=140.50], EntityPig['Pig'/507, l='MpServer', x=319.47, y=74.00, z=190.73], EntityBat['Bat'/1790, l='MpServer', x=366.37, y=22.17, z=95.53], EntityBat['Bat'/511, l='MpServer', x=332.69, y=20.10, z=190.35], EntityBat['Bat'/1791, l='MpServer', x=309.88, y=20.79, z=147.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by shadowfacts** [comment] 2017-03-21 22:26
Duplicate of #642.

**Closed as completed by shadowfacts** 2017-03-21 22:26 UTC
Labels: duplicate
