### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tulinekartul** [simeonradivoev/MatterOverdrive#471] opened 2016-03-19 14:31 UTC
Brief explanation of problem: says Process exited with code -1.

Steps to reproduce:

Crash report paste (if any) on [gist](gist.github.com): https://gist.github.com/tulinekartul/44a92b4323a4c546fe05

MatterOverdrive version: 0.4.2 build-22

Minecraft version: 1.8.9

Java version: 8

**Comment by simeonradivoev** [comment] 2016-03-19 14:33
Duplicate of #470. Use the latest 1.7.10 version of the dev builds. Not the 1.8.9 version which is not released.

**Comment by ajthemacboy** [comment] 2016-03-19 14:34
@simeonradivoev Maybe you should change the issue template, all these redundant issues...

**Closed by simeonradivoev** 2016-03-19 14:33 UTC

**Comment by simeonradivoev** [comment] 2016-03-19 14:35
@shadowfacts is in charge of the issues template

**Comment by shadowfacts** [comment] 2016-03-19 14:36
@ajthemacboy There will be duplicate issues no matter what, the issue template means they (usually) provide the minimum amount of information to start diagnosing an issue.
