### ISSUE TITLE
Random Crash while game play

### ISSUE THREAD

**Issue by LunarW15** [simeonradivoev/MatterOverdrive#658] opened 2017-03-19 14:01 UTC
Description: When you eat food, it causes a crash.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.1.1.jar)
  IC2core (industrialcraft-2-2.6.173-ex110.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.239-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 17. 3. 19 오후 10:58
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at matteroverdrive.client.render.RenderWeaponsBeam.shouldRenderBeam(RenderWeaponsBeam.java:157)
	at matteroverdrive.client.render.RenderWeaponsBeam.lambda$renderOthers$2(RenderWeaponsBeam.java:88)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at matteroverdrive.client.render.RenderWeaponsBeam.renderOthers(RenderWeaponsBeam.java:86)
	at matteroverdrive.client.render.RenderWeaponsBeam.onRenderWorldLast(RenderWeaponsBeam.java:72)
	at matteroverdrive.client.RenderHandler.onRenderWorldLast(RenderHandler.java:270)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_770_RenderHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:512)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1888)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Alaberti** [comment] 2017-03-19 19:04
Same issue, version 0.5.1 http://pastebin.com/raw/p0bnJZcE.

**Comment by shadowfacts** [comment] 2017-03-19 19:09
Duplicate of #657

**Closed as completed by shadowfacts** 2017-03-19 19:09 UTC
