### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by flexmak** [simeonradivoev/MatterOverdrive#715] opened 2017-07-29 06:55 UTC
I think Matter Overdrive is incompatible with some mods:

https://pastebin.com/akc7s7cz

**Comment by erics465** [comment] 2017-08-05 11:52
Duplicate of #710

Until this is fixed in the mod, you can workaround this crash by either removing Extra Utilities or Tinker's Construct from your modpack, if you still want to use Matter Overdrive.

**Closed as completed** 2017-09-01 19:21 UTC
