### ISSUE TITLE
Crashes on creating new world

### ISSUE THREAD

**Issue by Acolox** [simeonradivoev/MatterOverdrive#570] opened 2016-08-01 23:05 UTC
On build for 1.8.9-36,as i am creating a new world i get a crash
Here's the report

```
 ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 02.08.16. 01:04
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at net.minecraft.server.integrated.IntegratedPlayerList.func_148542_a(SourceFile:31)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:102)
    at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.server.integrated.IntegratedPlayerList.func_148542_a(SourceFile:31)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:102)
    at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:60)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@66653607
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 96246968 bytes (91 MB) / 414187520 bytes (395 MB) up to 1029177344 bytes (981 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1902 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCHIJAAAA   Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCHIJAAAA   mo{0.4.2} [Matter Overdrive] (MatterOverdrive-1.8.9-0.4.2-build-36.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by shadowfacts** [comment] 2016-08-01 23:06
Can you reproduce it one 1.8.9? Can you reproduce it on 1.9.4?

**Comment by Muirrum** [comment] 2017-03-10 14:38
Closing due to unresponsive author.

**Closed by Muirrum** 2017-03-10 14:38 UTC
Labels: need more info
