### ISSUE TITLE
Register ores in OreDictionnary

### ISSUE THREAD

**Issue by medsal15** [simeonradivoev/MatterOverdrive#119] opened 2015-07-19 14:00 UTC
I have 1 reason to request this for players and 1 for you:
AOBD registers ores-ingots-blocks-nuggets to minecraft and make them compatible to a bunch of mods (I don't know how much, but it's probably enough). Mod compatibility includes TE4, TC4, EnderIO, Mekanism, RC, and more.

**Comment by simeonradivoev** [comment] 2015-07-19 14:09
What your asking is integration in other mods, not OreDictionnary support. OreDictionnary support means that if i have copper, then adding that to oreDictionary, makes it so that copper from other mods works as well as my copper. The problem is, no other mod have Tritanium or Dilithium ores.

**Comment by medsal15** [comment] 2015-07-19 14:25
Oh. I meant register your ores in the OreDictionnary (then you can remove TE4 integration)

**Comment by simeonradivoev** [comment] 2015-08-06 00:00
Closed in here dcac80789193ac27ca860ca6f69d4bf119a68c6d

**Closed by simeonradivoev** 2015-08-06 00:00 UTC
Labels: enhancement
