### ISSUE TITLE
Star Map Crash

### ISSUE THREAD

**Issue by NullMagic** [simeonradivoev/MatterOverdrive#136] opened 2015-07-25 01:48 UTC
Whenever I try to use the Star Map I get this crash: http://pastebin.com/CeK4Vtnt

**Comment by shadowfacts** [comment] 2015-07-25 01:50
This appears to be caused by the Magic Cookies mod as indicated by this line of the crash log:
```
at tschallacka.magiccookies.client.graphics.events.RenderEventHandler.fogDensityEvent(RenderEventHandler.java:282)
```

Please contact the author of Magic Cookies and report this bug to them as well (and reference this issue when you do) as this is likely a cross mod interaction bug.

**Comment by NullMagic** [comment] 2015-07-25 01:51
Awesome, Will do

**Comment by shadowfacts** [comment] 2015-07-25 01:52
btw, the Magic Cookies issue page: https://github.com/tschallacka/MagicCookies/issues

**Comment by simeonradivoev** [comment] 2015-07-25 01:53
Ah, It's because I use a RougeAndroid Entity as the ViewRenderEntity and Magic Cookies casts it to a Entity Player.

**Comment by shadowfacts** [comment] 2015-07-25 01:54
Yeah, I presumed Magic Cookies forgot an `instanceof`` check, but unfortunately I can't PR because it's not Open Source :(

**Comment by NullMagic** [comment] 2015-07-27 01:39
Sorry, I missed your question about mod pack. I'm currently putting together the next version of the Devour The World modpack (http://devourtheworld.enjin.com/home), we're pretty small so it wouldn't be surprising if you'd never heard of us.

**Comment by tschallacka** [comment] 2015-07-27 06:20
Hmmh, I'm gonna look into it. i'm close to releasing a small update with patches and stuff, I'll take this along too in Magic Cookies. And yea, I forgot an instanceof check, but looking at the code, it shouldn't have supplied it...

But, then again, someone has been hitting the grog and gotten drunk... so badly he crashed :-P

**Comment by shadowfacts** [comment] 2016-02-12 14:35
Fixed by the Magic Cookies dev.

**Closed by shadowfacts** 2016-02-12 14:35 UTC
Labels: bug, mod compatibility  bug
