### ISSUE TITLE
Matter Overdrive 0.5.1 [1.10.2] Incompatibility Crash

### ISSUE THREAD

**Issue by BrendanatorX** [simeonradivoev/MatterOverdrive#656] opened 2017-03-19 09:32 UTC
Hi, I'm not sure if this has been reported yet but I'm very excited to be able to play Matter Overdrive in a more up to date mc version but I've noticed that Matter Overdrive crashes MC during the forge loadup due to an incompatibility, I'm afraid I don't know which one to help fix the issue faster but if you were to for example add it to the 1.10.2 curse mod pack ArdentCraft The Beginning and cancel/delete a bunch of mods at a time, you may find it that way.
Best of luck, I hope something can be done about it!

**Comment by Alaberti** [comment] 2017-03-19 16:09
I think it might help the devs more if you tossed them a crash log

**Comment by Muirrum** [comment] 2017-03-21 22:47
@BrendanatorX Yeah, but please put it here: https://pastebin.com or here: https://hastebin.com

**Comment by BrendanatorX** [comment] 2017-03-21 23:28
The MC launcher says 
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)" 
I'm sure you've read the same standard exception line before but just incase.
The crash log is located here: http://pastebin.com/wRRnPMr7

**Comment by shadowfacts** [comment] 2017-03-22 00:21
Duplicate of #631.

**Closed as completed by shadowfacts** 2017-03-22 00:21 UTC
Labels: duplicate
