### ISSUE TITLE
A fatal error has occurred this connection is terminated

### ISSUE THREAD

**Issue by KajesLorian** [simeonradivoev/MatterOverdrive#556] opened 2016-06-25 04:27 UTC
Brief explanation of problem: Whenever I join my server, after the initial load, if I try to walk anywhere I disconnect with "a fatal error has occurred this connection is terminated". Attempting to rejoin immediately causes same disconnect. If I restart I'm fine during the initial load, then it happens again. No problem if I open the same world in single player.

Steps to reproduce: simply logging on to server and moving around

Mods List: http://pastebin.com/sBaXEYin

MatterOverdrive version:0.4.1

Minecraft version:1.7.10

**Comment by KajesLorian** [comment] 2016-06-25 04:48
From My Client Log: http://pastebin.com/qxzRiQWP

**Comment by BlackAce21** [comment] 2016-06-25 19:32
The problem is you have too many mods that are registering global ID's of which there is a hard limit. It is discussed in detail here https://github.com/MinecraftForge/MinecraftForge/issues/1703

This mod SHOULD be changed to no longer use the EntityRegistry.registerGlobalEntityID but to fix your particular issue you simply need to remove some mods that add entities and pester the crap out of the devs of each mod to switch from using the global system to their own ;)

Also not all mods use the global entity registry so please don't take that as incentive to go confront every mod author on your list xD but enough of them are that you have overloaded the 255 entity limit of the vanilla registry system.

**Comment by KajesLorian** [comment] 2016-06-26 03:36
Okay. Thank you for that complete explanation. I shall see what I can live without!

**Comment by simeonradivoev** [comment] 2016-07-03 18:38
It's fixed in 1.8+ version of the mod

**Closed by simeonradivoev** 2016-07-03 18:38 UTC
