### ISSUE TITLE
negative gravitational anomaly mass

### ISSUE THREAD

**Issue by beepbeat** [simeonradivoev/MatterOverdrive#233] opened 2015-09-23 16:51 UTC
After throwing some (10-15 each) stacks of Blocks with high matter value (namely Diamond Blocks and Destabilized Redstone Bedrockium Drums) the Mass went negative
![2015-09-23_18 29 18](https://cloud.githubusercontent.com/assets/7950771/10051847/ebb813c2-6223-11e5-8aec-eda8b91e4c46.png)

**Comment by simeonradivoev** [comment] 2015-09-23 18:26
What Version of the Mod are you using ?

**Comment by beepbeat** [comment] 2015-09-23 19:15
1.7.10-0.4.0-RC3

**Comment by simeonradivoev** [comment] 2015-09-24 13:54
I can't seem to reproduce that. The negative Gravitational anomaly was fixed in version RC2. As of RC2 the mass of the Gravitational anomaly can reach 9,223,372,036,854,775,80. After that it will turn negative. Unless you changed the matter value of a block to a really high amount. This shouldn't be happening.

**Comment by simeonradivoev** [comment] 2015-09-24 13:55
You can try the newest version of the mod and try and reproduce the result in another anomaly and tell me if it's still happening.

**Comment by beepbeat** [comment] 2015-09-25 18:36
I can reproduce it every single time with an stack of octuple compressed cobblesstone (calculated as 43,05M kM) when the anomaly's mass is over 3000/4000 (below it has Problems eating the stack) 

done with version 1.7.10-0.4.0-rc4-build-99

**Comment by Badcholo** [comment] 2015-09-26 03:21
I think when the Anomaly Gets to a good max size, It should just Explode. The End. No more anomaly. That should keep players from trying to make a crazy super nova setup that will lag the server. 
Maybe it can have it's max size increased with the Stabilizers. Too big and BOOM!!

**Comment by simeonradivoev** [comment] 2015-09-26 13:46
Yes i was able to reproduce it by throwing about 3 - 4 stacks of octuple compressed cobblestone. It seems that even a Long integer is not enough then :laughing:

**Comment by beepbeat** [comment] 2015-09-26 14:35
Probably the easiest way is to remove the tile and block from the world if the mass goes negative

**Comment by simeonradivoev** [comment] 2015-09-26 14:37
Where is the fun in that! I will try and make it grow indefinitely.

**Comment by simeonradivoev** [comment] 2015-09-26 15:11
Ah silly me. The problem was not what I expected. It would take 334787849  octuple compressed cobblestone stacks for Long overflow.

**Closed** 2015-09-26 16:34 UTC
Labels: bug
