### ISSUE TITLE
More files than MatterScanner.java use Realms ChatFormatting instead of MC TextFormatting

### ISSUE THREAD

**Issue by Lazarix** [simeonradivoev/MatterOverdrive#506] opened 2016-05-15 20:20 UTC
Brief explanation of problem: Server crashes because of ChatFormatting

Steps to reproduce: download repo, compile and run server

Crash report paste (if any) on [gist](gist.github.com):

MatterOverdrive version: 1.9-0.4.3

Minecraft version: 1.9.4

**Comment by Lazarix** [comment] 2016-05-15 20:26
If you go into the src/main/java/matteroverdrive folder and do a grep -r "ChatFormatting" . you'll find that a lot of files are using ChatFormatting and causing a crash.

**Comment by shadowfacts** [comment] 2016-05-15 20:46
Duplicate of #504, already fixed.

**Comment by Lazarix** [comment] 2016-05-15 21:15
@shadowfacts Please re-read the title of the bug. #504 is for MatterScanner.java which I said is already fixed. There are a lot more files that have the same bug in it that haven't been updated.
If you compile the current binary and try to run it, it crashes.

**Comment by Lazarix** [comment] 2016-05-15 21:21
i.e. https://gist.github.com/Lazarix/e228a79aebf0398a78cf69df2c199040

**Comment by shadowfacts** [comment] 2016-05-15 21:37
Oh, GitHub was only searching the 1.8.9 branch >.<

**Comment by shadowfacts** [comment] 2016-05-15 22:18
03c60a47d438fe957150533b42b56e3397dfe5ff

**Closed by shadowfacts** 2016-05-15 22:18 UTC
Labels: duplicate

**Comment by Lazarix** [comment] 2016-05-16 00:07
Thanks @shadowfacts, that's solved that problem. #507 is now occurring. I've tried to solve it by moving the translateToLocal sections to the bottom and adding a @SideOnly(Side.CLIENT) (along with the required includes) but no dice.
