### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DeathRaye** [simeonradivoev/MatterOverdrive#641] opened 2017-03-13 23:17 UTC
[crash-2017-03-13_19.14.06-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/839860/crash-2017-03-13_19.14.06-client.txt)

**Comment by shadowfacts** [comment] 2017-03-13 23:20
Duplicate of #631.

**Closed as completed by shadowfacts** 2017-03-13 23:20 UTC
Labels: duplicate
