### ISSUE TITLE
Crash I've been getting

### ISSUE THREAD

**Issue by Hunterreaper** [simeonradivoev/MatterOverdrive#661] opened 2017-03-21 22:00 UTC
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo) Not sure what that means and what is causing it

**Comment by shadowfacts** [comment] 2017-03-21 22:02
Post the entire crash report.

**Comment by Muirrum** [comment] 2017-03-21 22:03
But please use either hastebin or pastebin.

**Comment by Hunterreaper** [comment] 2017-03-21 22:38
sorry first time doing this.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  FCFMLCorePlugin (FinderCompass-1.10.2.jar)
  CCLCorePlugin (CodeChicken Lib.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/21/17 5:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)
Caused by: net.minecraft.util.ReportedException: Generating mipmaps for frame
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:335)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:60)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at matteroverdrive.client.render.RenderParticlesHandler.<init>(RenderParticlesHandler.java:68)
	at matteroverdrive.client.RenderHandler.init(RenderHandler.java:209)
	at matteroverdrive.proxy.ClientProxy.init(ClientProxy.java:130)
	at matteroverdrive.MatterOverdrive.init(MatterOverdrive.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329132776 bytes (313 MB) / 717766656 bytes (684 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChicken Lib.jar) 
	UCHI	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3 (1).jar) 
	UCHI	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChicken Lib.jar) 
	UCHI	CodeChickenCore{2.3.4.89} [CodeChicken Core] (CodeChicken Core.jar) 
	UCHI	cofhcore{4.1.0} [CoFH Core] (CoFHCore-1.10.2-4.1.0.155-universal.jar) 
	UCHI	EnderStorage{2.1.5.80} [EnderStorage] (EnderStorage.jar) 
	UCHI	JEI{3.13.6.387} [Just Enough Items] (Just Enough Items.jar) 
	UCHI	extrautils2{1.0} [Extra Utilities 2] (Extra Utilities 2.jar) 
	UCHI	FinderCompass{1.10} [Finder Compass] (FinderCompass-1.10.2.jar) 
	UCHI	grapplemod{1.10-v7} [Grappling hook mod] (grapplemod-1.10.2-v7.jar) 
	UCHI	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited (1).jar) 
	UCHI	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle.jar) 
	UCHI	shadowmc{3.6.1} [ShadowMC] (ShadowMC.jar) 
	UCHI	tesla{1.2.1.50} [TESLA] (TESLA.jar) 
	UCHE	mo{0.5.1} [Matter Overdrive] (Matter Overdrive.jar) 
	UCHI	metamorph{1.0.2} [Metamorph] (Metamorph.jar) 
	UCHI	thermalfoundation{2.0.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.3.77-universal.jar) 
	UCHI	thermalexpansion{5.0.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.3.86-universal.jar) 
	UCHI	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (Tinkers' Construct.jar) 
	UCHI	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHI	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHI	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.197.jar) 
	UCHI	wawla{2.3.0.194} [What Are We Looking At] (Wawla-1.10.2-2.3.0.197.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
FCFMLCorePlugin (FinderCompass-1.10.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
CCLCorePlugin (CodeChicken Lib.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
		CodeChickenCore has an invalid fingerprint.
		EnderStorage has an invalid fingerprint.
```

**Comment by shadowfacts** [comment] 2017-03-21 22:43
Duplicate of #631.

**Closed as completed by shadowfacts** 2017-03-21 22:43 UTC
Labels: duplicate

**Comment by Muirrum** [comment] 2017-03-21 22:46
What the hell did I say? Please. For the love of god. Use pastebin.
