### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Tyrantin** [simeonradivoev/MatterOverdrive#681] opened 2017-04-09 13:15 UTC
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at matteroverdrive.client.render.RenderWeaponsBeam.shouldRenderBeam(RenderWeaponsBeam.java:157)
	at matteroverdrive.client.render.RenderWeaponsBeam.lambda$renderOthers$2(RenderWeaponsBeam.java:88)
	at matteroverdrive.client.render.RenderWeaponsBeam$$Lambda$1473/810163224.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at matteroverdrive.client.render.RenderWeaponsBeam.renderOthers(RenderWeaponsBeam.java:86)
	at matteroverdrive.client.render.RenderWeaponsBeam.onRenderWorldLast(RenderWeaponsBeam.java:72)
	at matteroverdrive.client.RenderHandler.onRenderWorldLast(RenderHandler.java:270)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1007_RenderHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

**Comment by shadowfacts** [comment] 2017-04-09 13:22
Duplicate of #674, #666, and #636. You've submitted the same crash report **four times** now. Please take a _cursory_ look at existing issues to see if the one you're reporting has already been submitted.

If you continue to post duplicate issues of this, I will block you from posting here.

**Closed as completed by shadowfacts** 2017-04-09 13:22 UTC
Labels: duplicate
