### ISSUE TITLE
Crash when launching game

### ISSUE THREAD

**Issue by TheT0xicPanda** [simeonradivoev/MatterOverdrive#646] opened 2017-03-14 21:29 UTC
`Time: 3/14/17 5:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)
Caused by: net.minecraft.util.ReportedException: Generating mipmaps for frame
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:468)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:60)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:213)
	at matteroverdrive.client.render.RenderParticlesHandler.<init>(RenderParticlesHandler.java:68)
	at matteroverdrive.client.RenderHandler.init(RenderHandler.java:209)
	at matteroverdrive.proxy.ClientProxy.init(ClientProxy.java:130)
	at matteroverdrive.MatterOverdrive.init(MatterOverdrive.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException
`

**Comment by shadowfacts** [comment] 2017-03-14 21:33
Duplicate of #631.

**Closed as completed by shadowfacts** 2017-03-14 21:33 UTC
Labels: duplicate

**Comment by TheT0xicPanda** [comment] 2017-03-14 21:36
You marked it as duplicate but my issue wasn't resolved in the other post D: how do i fix this?

**Comment by shadowfacts** [comment] 2017-03-14 21:40
I don't know (yet). Your issue was closed because it very quickly gets annoying to have many issues open on the issue tracker all of which are about the same bug.

**Comment by TheT0xicPanda** [comment] 2017-03-14 21:44
its odd cause it works on the server

**Comment by shadowfacts** [comment] 2017-03-14 21:48
Yes, the crash has to do with texture loading, which only happens on the client.

**Comment by TheT0xicPanda** [comment] 2017-03-14 22:06
its tinkers also, because Mo works with extrautils but no tinker. but with tinker all 3 together dont work

**Comment by Jacob345k** [comment] 2017-07-21 07:45
This is still happening

**Comment by Muirrum** [comment] 2017-07-21 10:58
And yet it is closed, because it is a duplicate.
