### ISSUE TITLE
Generating mipmaps for frame

### ISSUE THREAD

**Issue by 1matto** [simeonradivoev/MatterOverdrive#677] opened 2017-04-02 15:21 UTC
[crash-2017-04-02_11.16.37-client.txt](https://github.com/simeonradivoev/MatterOverdrive/files/888443/crash-2017-04-02_11.16.37-client.txt)

**Comment by shadowfacts** [comment] 2017-04-02 15:28
Duplicate of #631. Please search the issue tracker before posting to see if your issue has already been submitted.

**Closed as completed by shadowfacts** 2017-04-02 15:28 UTC
Labels: duplicate
