### ISSUE TITLE
NullPointerException: Ticking entity, mod incompatibility 

### ISSUE THREAD

**Issue by lightning02** [simeonradivoev/MatterOverdrive#489] opened 2016-04-21 17:28 UTC
Brief explanation of problem: This happens when you try to break an ender chest with omni tool 

Crash report paste (if any) on [gist](gist.github.com): http://pastebin.com/XkGTfcfS

MatterOverdrive version: 0.4.1-build-35

Minecraft version: 1.7.10

**Comment by simeonradivoev** [comment] 2016-04-21 17:29
The crash was actually caused by enderstorage. I will have to look into it.

**Comment by shadowfacts** [comment] 2016-07-24 00:53
Dupe of #499

**Closed by shadowfacts** 2016-07-24 00:53 UTC
Labels: mod compatibility
