### ISSUE TITLE
Bucket Crash On Client

### ISSUE THREAD

**Issue by VexTheWanderer01** [simeonradivoev/MatterOverdrive#670] opened 2017-03-27 13:46 UTC
While right clicking with a bucket on air without using the bucket, i get a crash:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  HFTransformer (Harvest-Festival-1.10.2-0.5.23.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/26/17 1:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at matteroverdrive.handler.BucketHandler.onBucketFill(BucketHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_458_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:336)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at matteroverdrive.handler.BucketHandler.onBucketFill(BucketHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_458_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:336)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MidnightTheCorgi'/147125, l='MpServer', x=-369.92, y=70.17, z=1125.75]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (192,64,216), Chunk: (at 0,4,8 in 12,13; contains blocks 192,0,208 to 207,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1174550 game time, 1153938 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityItem['item.tile.torch'/159874, l='MpServer', x=-368.88, y=34.00, z=1068.28], EntityItem['item.tile.torch'/159873, l='MpServer', x=-373.33, y=39.00, z=1094.13], EntityItem['item.tile.torch'/159878, l='MpServer', x=-378.57, y=34.00, z=1162.49], EntityCartChest['Chest Cart'/159879, l='MpServer', x=-382.50, y=28.06, z=1193.50], EntityItem['item.tile.torch'/159876, l='MpServer', x=-371.59, y=43.00, z=1076.13], EntityItem['item.tile.torch'/159877, l='MpServer', x=-382.61, y=33.00, z=1077.97], EntityCalfFriesian['Friesian Calf'/159882, l='MpServer', x=-371.44, y=68.00, z=1126.27], EntitySowYorkshire['Yorkshire Sow'/159883, l='MpServer', x=-370.53, y=67.00, z=1123.45], EntityCowFriesian['Friesian Cow'/159880, l='MpServer', x=-370.00, y=67.00, z=1126.60], EntityBullFriesian['Friesian Bull'/159881, l='MpServer', x=-374.30, y=72.00, z=1124.68], EntityHogYorkshire['Yorkshire Hog'/159886, l='MpServer', x=-368.50, y=75.00, z=1147.50], EntityPigletYorkshire['Yorkshire Piglet'/159884, l='MpServer', x=-367.80, y=65.00, z=1119.47], EntityPigletYorkshire['Yorkshire Piglet'/159885, l='MpServer', x=-369.50, y=75.00, z=1144.50], EntityBat['Bat'/163990, l='MpServer', x=-328.50, y=54.10, z=1108.50], EntityItem['item.tile.sapling.oak'/159642, l='MpServer', x=-415.88, y=19.00, z=1092.30], EntitySowYorkshire['Yorkshire Sow'/159643, l='MpServer', x=-412.50, y=79.00, z=1175.31], EntitySowYorkshire['Yorkshire Sow'/159644, l='MpServer', x=-415.50, y=79.00, z=1172.50], EntityBat['Bat'/164002, l='MpServer', x=-390.02, y=40.58, z=1097.70], EntityItem['item.tile.mushroom9'/159786, l='MpServer', x=-385.08, y=14.00, z=1069.13], EntityItem['item.tile.dungeontactics:flower_ailment'/159787, l='MpServer', x=-389.88, y=54.00, z=1068.03], EntityItem['item.tile.torch'/159790, l='MpServer', x=-385.13, y=34.00, z=1148.23], EntityItem['item.tile.rail'/159788, l='MpServer', x=-399.58, y=39.00, z=1112.19], EntityItem['item.tile.rail'/159789, l='MpServer', x=-389.74, y=39.00, z=1112.32], EntityItem['item.tile.torch'/160182, l='MpServer', x=-361.03, y=35.00, z=1161.43], EntityPlayerSP['MidnightTheCorgi'/147125, l='MpServer', x=-369.92, y=70.17, z=1125.75], EntityCartChest['Chest Cart'/160183, l='MpServer', x=-353.50, y=35.06, z=1177.50], EntityItem['item.tile.torch'/160180, l='MpServer', x=-355.55, y=39.00, z=1091.15], EntityCartChest['Chest Cart'/160181, l='MpServer', x=-358.50, y=39.06, z=1162.50], EntityCartChest['Chest Cart'/160184, l='MpServer', x=-364.50, y=25.06, z=1187.50], EntityHedgehog['Hedgehog'/160446, l='MpServer', x=-338.21, y=63.01, z=1139.26], EntityItem['item.tile.torch'/160447, l='MpServer', x=-351.13, y=39.00, z=1096.81], EntityBat['Bat'/163647, l='MpServer', x=-361.50, y=34.23, z=1144.61], EntityBat['Bat'/164031, l='MpServer', x=-363.34, y=23.95, z=1127.75], EntityCowHereford['Hereford Cow'/159420, l='MpServer', x=-421.50, y=83.00, z=1162.50], EntityBat['Bat'/160701, l='MpServer', x=-433.85, y=31.31, z=1092.76], EntityItem['item.tile.torch'/160445, l='MpServer', x=-345.28, y=34.00, z=1143.05], EntitySowYorkshire['Yorkshire Sow'/159421, l='MpServer', x=-420.50, y=79.00, z=1175.50], EntityCartChest['Chest Cart'/160451, l='MpServer', x=-319.50, y=34.06, z=1124.50], EntityBat['Bat'/164037, l='MpServer', x=-392.62, y=40.11, z=1110.38], EntityBat['Bat'/163787, l='MpServer', x=-368.45, y=32.03, z=1059.55], EntityCartChest['Chest Cart'/160334, l='MpServer', x=-363.50, y=28.06, z=1244.50], EntityCartChest['Chest Cart'/160484, l='MpServer', x=-314.50, y=38.06, z=1104.50], EntityBat['Bat'/163690, l='MpServer', x=-362.21, y=35.57, z=1079.76], EntityCartChest['Chest Cart'/160489, l='MpServer', x=-365.50, y=27.06, z=1256.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 631358400 bytes (602 MB) / 3140747264 bytes (2995 MB) up to 3140747264 bytes (2995 MB)
	JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2115 Optifine OptiFine_1.10.2_HD_U_D7 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2115.jar) 
	UCHIJA	Forge{12.18.2.2115} [Minecraft Forge] (forge-1.10.2-12.18.2.2115.jar) 
	UCHIJA	advancedswords{1.3.0} [Advanced Swords] (advancedswords-1.3.0-[1.9.4].jar) 
	UCHIJA	animania{1.0.4.1} [Animania] (animania-1.10-1.0.4.1.jar) 
	UCHIJA	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJA	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJA	JEI{3.14.6.412} [Just Enough Items] (jei_1.10.2-3.14.6.412.jar) 
	UCHIJA	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCHIJA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJA	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJA	tesla{1.2.1.50} [TESLA] (Tesla-1.10.2-1.2.1.50.jar) 
	UCHIJA	thedragonlib{1.10.2-1.3.1} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.1.jar) 
	UCHIJA	armorplus{1.10.2-8.5.0.1} [ArmorPlus] (armorplus-1.10.2-8.5.0.1.jar) 
	UCHIJA	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	UCHIJA	BetterAchievements{0.3.0.30} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.30.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2089} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2089-universal.jar) 
	UCHIJA	infinitylib{1.10.2-@MAJOR@.@MINOR@.@REVIS@} [InfinityLib] (infinityLib-0.1.jar) 
	UCHIJA	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.1.jar) 
	UCHIJA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJA	buttons{1.10.2-0.0.3-3} [Buttons] (Buttons-1.10.2-0.0.3-3.jar) 
	UCHIJA	chancecubes{1.10.2-2.3.2.131} [Chance Cubes] (ChanceCubes-1.10.2-2.3.2.131.jar) 
	UCHIJA	chiselsandbits{12.6} [Chisels & Bits] (chiselsandbits-12.6.jar) 
	UCHIJA	claybucket{1.1} [Clay Bucket] (ClayBucket-1.9.4-1.1.jar) 
	UCHIJA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJA	cxlibrary{1.2.3} [CXLibrary] (cxlibrary-1.10.2-1.2.3.jar) 
	UCHIJA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.5_1.10.2.jar) 
	UCHIJA	props{2.3.4} [Decocraft] (Decocraft-2.3.5_1.10.2.jar) 
	UCHIJA	DungeonTactics{DT0.10.0} [DungeonTactics] (DungeonTactics-1.10.2-0.10.0.jar) 
	UCHIJA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.2.jar) 
	UCHIJA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.2.jar) 
	UCHIJA	forestry{5.2.16.331} [Forestry] (forestry_1.10.2-5.2.16.331.jar) 
	UCHIJA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJA	harvestfestival{0.5.23} [Harvest Festival] (Harvest-Festival-1.10.2-0.5.23.jar) 
	UCHIJA	HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.9.4-1.0.0.jar) 
	UCHIJA	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	itemscroller{0.7.1} [Item Scroller] (itemscroller-1.10.2-0.7.1.jar) 
	UCHIJA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJA	justenoughbuttons{1.10.2-1.6.3} [Just Enough Buttons] (justenoughbuttons-1.10.2-1.6.3.jar) 
	UCHIJA	jeresources{0.5.7.96} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.96.jar) 
	UCHIJA	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
	UCHIJA	levels{r4.1.3} [Levels] (Levels-1.10.2-r4.1.3.jar) 
	UCHIJA	login_shield{1.10.2-14-g4618728} [Login Shield] (Login_Shield-1.10.2-14-g4618728.jar) 
	UCHIJA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	mo{0.5.1} [Matter Overdrive] (MatterOverdrive-1.10.2-0.5.1.jar) 
	UCHIJA	minecolonies{1.10.2-0.4.1870} [MineColonies] (minecolonies-universal-1.10.2-0.4.1870.jar) 
	UCHIJA	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHIJA	moreoverlays{1.8} [MoreOverlays] (moreoverlays-1.8-mc1.10.2.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	ping{1.2.2} [Ping] (Ping-1.10.X-1.2.2.B7-universal.jar) 
	UCHIJA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJA	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCHIJA	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCHIJA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJA	RTG{4.1.1.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.4.jar) 
	UCHIJA	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHIJA	stevescarts{2.1.0.59} [Steve's Carts 2] (StevesCarts-1.10.2-2.1.0.59.jar) 
	UCHIJA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJA	waddles{0.5.0} [Waddles] (Waddles-1.10.2-0.5.0.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	UCHIJA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
HFTransformer (Harvest-Festival-1.10.2-0.5.23.jar)
  joshie.harvest.asm.HFTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4542' Renderer: 'Intel(R) HD Graphics 520'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Launched Version: forge-12.18.2.2115
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4542, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4542
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by shadowfacts** [comment] 2017-03-27 13:47
Duplicate of #662.

Holy hell, is nobody capable of searching the issue tracker and seeing that the issue they're reporting has already been reported (multiple) times?

**Closed as completed by shadowfacts** 2017-03-27 13:47 UTC
Labels: duplicate

**Comment by VexTheWanderer01** [comment] 2017-03-27 14:55
i have 0.5.1 and it still crashes...

**Comment by shadowfacts** [comment] 2017-03-27 14:58
Yes, because it's been fixed for 0.5.2. If you looked at the other reports, you would see that they were also using 0.5.1.
